version: '3'
services:
  frontend:
    build:
      context: ./ui-web-app-reactjs
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:8080
    image: frontend:1.0
    container_name: frontend
    networks:
      - frontend
  api-gateway:
    build:
      context: ./zuul-api-gateway
      dockerfile: Dockerfile
      target: builder
    restart: always
    ports:
      - 9999:9999
    image: api-gateway:1.0
    container_name: api-gateway
    networks:
      - backend
      - frontend
  cart:
    build: 
      context: ./cart-microservice-nodejs/
      dockerfile: Dockerfile
    restart: always
    ports:
    - 1004:1004
    image: cart:1.0
    container_name: cart
    networks:
      - backend
  eureka:
    build:
      context: ./eureka-discovery-server/
      dockerfile: Dockerfile
    image: eureka:1.0
    ports:
      - 8761:8761
    container_name: eureka
    networks:
      - backend
  offers:
    build:
      context: ./offers-microservice-spring-boot/
      dockerfile: Dockerfile
      target: builder
    image: offers:1.0
    container_name: offers
    ports:
      - 1001:1001
    networks:
      - backend      
  shoes:
    build:
      context: ./shoes-microservice-spring-boot/
      dockerfile: Dockerfile
    image: shoes:1.0
    container_name: shoes
    ports:
      - 1002:1002
    networks:
      - backend      
  wishlist:
    build:
      context: ./wishlist-microservice-python/
      dockerfile: Dockerfile
    image: wishlist:1.0
    container_name: wishlist
    ports:
      - 1003:1003
    networks:
      - backend

networks:
  frontend:
  backend:
    
    
  
  

    
