# FROM maven as build

# WORKDIR /app
# COPY . .
# RUN mvn install

# #jdk
# FROM openjdk:11.0.10-jre
# WORKDIR /app
# COPY --from=build /app/target/zuul-0.0.1-SNAPSHOT.jar /app 

# EXPOSE 9999

# CMD ["java", "-jar", "zuul-0.0.1-SNAPSHOT.jar"] 

FROM maven as builder

WORKDIR /app

COPY . /app

RUN mvn install -Dmaven.test.skip
# for a single dockerfile you only have one CMD or entrypoint script

FROM openjdk:11.0.10-jre

WORKDIR /app

COPY --from=builder /app/target/zuul-0.0.1-SNAPSHOT.jar /app/

EXPOSE 9999

CMD ["java","-jar","zuul-0.0.1-SNAPSHOT.jar"]




