pipeline{
    agent any

    environment {

       def KUBE = credentials('aws-kubeconfig')
       def HELM_CHART_NAME = "web"
       def CHART_DIRECTORY =  "../k8s/"
       def REGI_NAME ="chakravarthy712"
        
    }

    stages{
        stage("Git Checkout"){
            steps{
                git 'https://github.com/Chakravarthy7102/Gateway-Micro.git'
            }
        }

        stage("Docker Build"){
            steps{
                sh 'docker build --tag gateway:${BUILD_NUMBER}'
                sh 'docker images'
            }
        }

        stage("Docker Push"){
            steps{
                sh 'docker push ${REGI_NAME}/gateway:${BUILD_NUMBER}'
                sh 'docker rmi ${REGI_NAME}/gateway:${BUILD_NUMBER}'
            }
        }

        stage("Kubernetes apply"){
            steps{
                // sh 'cat ../k8s/templates/gateway-deployment.yaml | grep -i image'
                // sh 'sed -i 's/image: gateway:*/image: gateway:"${BUILD_NUMBER}"/' ../k8s/templates/gateway-deployment.yaml '
                // sh 'kubectl --kubeconfig $KUBE apply -f ../k8s/templates/gateway-deployment.yaml'/
                sh 'helm list'
                sh 'helm lint ${CHART_DIRECTORY}'
                sh 'helm upgrade --set frontend.image.tag=${BUILD_NUMBER} ${HELM_CHART_NAME} ${CHART_DIRECTORY} '
            }
        }

    }
}