pipeline{
    agent any

    environment {
        KUBE = credentials('kubeconfig')
    }


    stages{
        stage("Git Checkout"){
            steps{
                git 'https://github.com/Chakravarthy7102/Gateway-Micro.git'
            }
        }

        stage("Docker Build"){
            steps{
                sh 'docker build --tag offers:${env.BUILD_NUMBER}'
            }
        }

        stage("Docker Push"){
            steps{
                sh 'docker push chakravarthy712/offers:${env.BUILD_NUMBER}'
            }
        }

        stage("Kubernetes apply"){
            steps {
                sh 'cat ../k8s/templates/offers-deployment.yaml | grep -i image'
                sh 'sed -i 's/image: offers:*/image: offers:"${env.BUILD_NUMBER}"/' ../k8s/templates/offers-deployment.yaml '
                sh 'kubectl --kubeconfig $KUBE apply -f ../k8s/templates/offers-deployment.yaml'
            }
        }

    }
}