apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.eureka.labels.app }}-deployment

#TODO: add deployment startegy to each and every deployment file
spec:
  replicas: {{ .Values.eureka.replicaCount }}
  selector:
    {{- with .Values.eureka.labels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
    {{- with .Values.eureka.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: {{ .Values.eureka.image.name }}
          image: "{{ .Values.registry }}/{{ .Values.eureka.image.name }}:{{ .Values.eureka.image.tag }}"
          imagePullPolicy: {{ .Values.eureka.image.pullPolicy }}
          {{- with .Values.eureka.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.eureka.image.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}