apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.gateway.service.name }}-service

spec:
  type: {{ .Values.gateway.service.type }}
  {{- with .Values.gateway.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}


