apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.offers.service.name }}-service

spec:
  type: {{ .Values.offers.service.type }}
  {{- with .Values.offers.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.offers.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}

